# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    - go generate ./...
    - packr2
builds:
  - main: ./pkg/cli/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
archives:
  - name_template: >-
      glow_
      {{ .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ["zip"]
brews:
  - repository:
      owner: meinto
      name: glow
    commit_author:
      name: Tobias Meinhardt
      email: tobias.meinhardt@mailbox.org
    homepage: "https://github.com/meinto/glow"
    description: "A cli tool to adapt git-flow"
    directory: formula
    dependencies:
      - git
# snapcraft:
#   name_template: "glow_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
#   replacements:
#     386: i386
#     amd64: x86_64
#   summary: git flow cli tool.
#   description: |
#     glow is a cli tool to adapt git-flow.
#     https://github.com/meinto/glow
#   grade: stable
#   confinement: strict
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
