# This file was generated by GoReleaser. DO NOT EDIT.
class Glow < Formula
  desc ""
  homepage ""
  url "https://github.com/meinto/glow/releases/download/v1.10.0/glow_1.10.0_darwin_x86_64.tar.gz"
  version "1.10.0"
  sha256 "f328f3b1d4c0a12cd04c9d9e26567ea0621a1b98677dd7e73c7121efe1526f89"
  
  depends_on "git"

  def install
    bin.install "glow"
  end
end
